# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('follow_id', models.IntegerField()),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='MusicFavourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('Fmusic_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_favourite',
            },
        ),
        migrations.CreateModel(
            name='MusicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('Hmusic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_history',
            },
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_path', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=15)),
                ('play_No', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'music_list',
            },
        ),
        migrations.CreateModel(
            name='SingerInfo',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=15)),
                ('singer_pic', models.CharField(max_length=50)),
                ('singer_text', models.TextField()),
            ],
            options={
                'db_table': 'singer_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(max_length=11, unique=True)),
                ('user_nickname', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('保密', '保密')], default='保密', max_length=2)),
                ('birthday', models.CharField(default='1770-01-01', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('attention', models.IntegerField(default=0)),
                ('Fan', models.IntegerField(default=0)),
                ('image', models.CharField(default='user_pic/default/user.jpg', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
