# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-18 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=20)),
                ('friend_nickname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='MusicFavourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('Fmusic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_favourite',
            },
        ),
        migrations.CreateModel(
            name='MusicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('Hmusic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_history',
            },
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_path', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=15)),
                ('play_No', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'music_list',
            },
        ),
        migrations.CreateModel(
            name='SingerInfo',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=15)),
                ('singer_pic', models.CharField(max_length=50)),
                ('singer_text', models.TextField()),
            ],
            options={
                'db_table': 'singer_info',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='Fan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attention',
        ),
    ]
