# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_auto_20181018_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('friend_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='MusicFavourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('Fmusic_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_favourite',
            },
        ),
        migrations.CreateModel(
            name='MusicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('Hmusic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_history',
            },
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=50)),
                ('music_path', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=15)),
                ('play_No', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'music_list',
            },
        ),
        migrations.CreateModel(
            name='MusicSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
            ],
            options={
                'db_table': 'music_sheet',
            },
        ),
        migrations.CreateModel(
            name='UserSheet',
            fields=[
                ('sheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_sheet',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='Fan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='attention',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='user_pic/default/user.jpg', max_length=50),
        ),
    ]
