# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_musiclist_length_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiclist',
            old_name='length_name',
            new_name='length_time',
        ),
        migrations.AddField(
            model_name='musiclist',
            name='lrc_path',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
